In [2]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
#loading dataset

df = pd.read_csv('D:\\PROJECTS\\Projects\\creditcardfrauddetection\\fraudTest.csv')

In [5]:
df.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19   
1       302  Sales professional, IT  1990-01-17   
2     34496       Librarian, public  1970-10-21   
3     54767            Set designer  1987-07-25   
4      1126      Furniture designer  1955-07-06   

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

In [6]:
#dataset info
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Unnamed: 0             555719 non-null  int64  
 1   trans_date_trans_time  555719 non-null  object 
 2   cc_num                 555719 non-null  int64  
 3   merchant               555719 non-null  object 
 4   category               555719 non-null  object 
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object 
 7   last                   555719 non-null  object 
 8   gender                 555719 non-null  object 
 9   street                 555719 non-null  object 
 10  city                   555719 non-null  object 
 11  state                  555719 non-null  object 
 12  zip                    555719 non-null  int64  
 13  lat                    555719 non-null  float64
 14  long                   555719 non-nu

In [7]:
#checking the nuber of missing values in each column
df.isnull().sum()


Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [8]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [9]:
X = df.drop(columns=['is_fraud'])  # Assuming 'is_fraud' is the target variable
y = df['is_fraud']

In [10]:
# Assuming 'date_column' is the column with date/time values
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

df['year'] = df['trans_date_trans_time'].dt.year
df['month'] = df['trans_date_trans_time'].dt.month
df['day'] = df['trans_date_trans_time'].dt.day
df['hour'] = df['trans_date_trans_time'].dt.hour
df['minute'] = df['trans_date_trans_time'].dt.minute

# Now you have separate numeric features for date and time
# Accessing the 'year' column
year_column = df['year']

# Accessing the 'month' column
month_column = df['month']

# Accessing the 'day' column
day_column = df['day']

# Accessing the 'hour' column
hour_column = df['hour']

# Accessing the 'minute' column
minute_column = df['minute']



In [11]:
# Drop the 'date_column' if you haven't already
df = df.drop(columns=['trans_date_trans_time'])


In [12]:
df

Unnamed: 0            cc_num                              merchant  \
0                0  2291163933867244                 fraud_Kirlin and Sons   
1                1  3573030041201292                  fraud_Sporer-Keebler   
2                2  3598215285024754  fraud_Swaniawski, Nitzsche and Welch   
3                3  3591919803438423                     fraud_Haley Group   
4                4  3526826139003047                 fraud_Johnston-Casper   
...            ...               ...                                   ...   
555714      555714    30560609640617                 fraud_Reilly and Sons   
555715      555715  3556613125071656                  fraud_Hoppe-Parisian   
555716      555716  6011724471098086                       fraud_Rau-Robel   
555717      555717     4079773899158                 fraud_Breitenberg LLC   
555718      555718  4170689372027579                     fraud_Dare-Marvin   

              category     amt    first      last gender  \
0        personal_care    2.86     Jeff   Elliott      M   
1        personal_care   29.84   Joanne  Williams      F   
2       health_fitness   41.28   Ashley     Lopez      F   
3             misc_pos   60.05    Brian  Williams      M   
4               travel    3.19   Nathan    Massey      M   
...                ...     ...      ...       ...    ...   
555714  health_fitness   43.77  Michael     Olson      M   
555715       kids_pets  111.84     Jose   Vasquez      M   
555716       kids_pets   86.88      Ann    Lawson      F   
555717          travel    7.99     Eric   Preston      M   
555718   entertainment   38.13   Samuel      Frey      M   

                             street          city  ...  \
0                 351 Darlene Green      Columbia  ...   
1                  3638 Marsh Union       Altonah  ...   
2              9333 Valentine Point      Bellmore  ...   
3       32941 Krystal Mill Apt. 552    Titusville  ...   
4          5783 Evan Roads Apt. 465      Falmouth  ...   
...                             ...           ...  ...   
555714          558 Michael Estates         Luray  ...   
555715          572 Davis Mountains  Lake Jackson  ...   
555716   144 Evans Islands Apt. 683       Burbank  ...   
555717   7020 Doyle Stream Apt. 951          Mesa  ...   
555718     830 Myers Plaza Apt. 384        Edmond  ...   

                               trans_num   unix_time  merch_lat  merch_long  \
0       2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1       324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2       c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3       2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4       57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   
...                                  ...         ...        ...         ...   
555714  9b1f753c79894c9f4b71f04581835ada  1388534347  39.946837  -91.333331   
555715  2090647dac2c89a1d86c514c427f5b91  1388534349  29.661049  -96.186633   
555716  6c5b7c8add471975aa0fec023b2e8408  1388534355  46.658340 -119.715054   
555717  14392d723bb7737606b2700ac791b7aa  1388534364  44.470525 -117.080888   
555718  1765bb45b3aa3224b4cdcb6e7a96cee3  1388534374  36.210097  -97.036372   

        is_fraud  year month day  hour  minute  
0              0  2020     6  21    12      14  
1              0  2020     6  21    12      14  
2              0  2020     6  21    12      14  
3              0  2020     6  21    12      15  
4              0  2020     6  21    12      15  
...          ...   ...   ...  ..   ...     ...  
555714         0  2020    12  31    23      59  
555715         0  2020    12  31    23      59  
555716         0  2020    12  31    23      59  
555717         0  2020    12  31    23      59  
555718         0  2020    12  31    23      59  

[555719 rows x 27 columns]

In [13]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

Index(['merchant', 'category', 'first', 'last', 'gender', 'street', 'city',
       'state', 'job', 'dob', 'trans_num'],
      dtype='object')

In [14]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])


In [15]:
for column in categorical_columns:
    unique_values = df[column].unique()
    print(f"Unique values in '{column}': {unique_values}")


Unique values in 'merchant': [319 591 611 222 292 126 526 500 201 315 170 197 100  34 398 662 252 369
 437 489 109 621 646 656 378 258 366 154 382 296 164 689 451 402 551 264
  81 506 435 496 167 112  15 333 683  10 180  89  56 145 248 132 449 461
 457  28 536  45 663   5 484 220 690 679  38 310 174 561 209 199 144 213
 657  23 485 368 615 619 348 547 520 599 469 262  85 313 400 320 492 207
  14 257 675  76 179  33 515 452 557 490 571  46 531 314 433  67 226  74
 187 409  41   1 165 391 191 596 111 323 113 644  84 151 671 544 576 448
  13 388  22 456  61 460 104 362 139 660 541 123 312 421 651 136 392 546
   8 565 629 253 148 234 397 161 343 384 552  54 636 668 190 633 558 672
 420  75 614 540 171 317 102 574 512 529 418 125 192  95 532 471 188  69
 649 124 510 628 538 624   3 587 603  50 122 685 160 617 237 155 263 228
 277 283 606 686 385 350 195 486 265 601  82 501 438 502 256 577  66 143
 128 203 297 653 339 413 318 645 254 282 210 211 430  16 580 353  35 364
 383 236 412 316 344 5

In [16]:
# Separate features (X) and target (y)
X = df.drop(columns=['is_fraud'])  # Features
y = df['is_fraud']  # Target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the feature matrix
scaler = StandardScaler()
X_train_standardized = scaler.fit_transform(X_train)
X_test_standardized = scaler.transform(X_test)

In [17]:
X = df.drop(columns=['is_fraud'])  # Assuming 'is_fraud' is the target variable
y = df['is_fraud']

In [18]:
X

Unnamed: 0            cc_num  merchant  category     amt  first  last  \
0                0  2291163933867244       319        10    2.86    151   115   
1                1  3573030041201292       591        10   29.84    163   457   
2                2  3598215285024754       611         5   41.28     24   249   
3                3  3591919803438423       222         9   60.05     42   457   
4                4  3526826139003047       292        13    3.19    247   261   
...            ...               ...       ...       ...     ...    ...   ...   
555714      555714    30560609640617       507         5   43.77    235   315   
555715      555715  3556613125071656       264         7  111.84    171   424   
555716      555716  6011724471098086       496         7   86.88     18   239   
555717      555717     4079773899158        75        13    7.99    111   342   
555718      555718  4170689372027579       125         0   38.13    280   145   

        gender  street  city  ...  dob  trans_num   unix_time  merch_lat  \
0            1     341   157  ...  376      98699  1371816865  33.986391   
1            0     354    16  ...  760     108785  1371816873  39.450498   
2            0     865    61  ...  421     433979  1371816893  40.495810   
3            1     320   764  ...  718      71993  1371816915  28.812398   
4            1     548   247  ...  177     190585  1371816917  44.959148   
...        ...     ...   ...  ...  ...        ...         ...        ...   
555714       1     531   443  ...  334     336391  1388534347  39.946837   
555715       1     540   401  ...  890      70372  1388534349  29.661049   
555716       0     126   104  ...  609     235088  1388534355  46.658340   
555717       1     663   476  ...  331      43546  1388534364  44.470525   
555718       1     778   224  ...  813      50595  1388534374  36.210097   

        merch_long  year  month  day  hour  minute  
0       -81.200714  2020      6   21    12      14  
1      -109.960431  2020      6   21    12      14  
2       -74.196111  2020      6   21    12      14  
3       -80.883061  2020      6   21    12      15  
4       -85.884734  2020      6   21    12      15  
...            ...   ...    ...  ...   ...     ...  
555714  -91.333331  2020     12   31    23      59  
555715  -96.186633  2020     12   31    23      59  
555716 -119.715054  2020     12   31    23      59  
555717 -117.080888  2020     12   31    23      59  
555718  -97.036372  2020     12   31    23      59  

[555719 rows x 26 columns]

In [19]:
y

0         0
1         0
2         0
3         0
4         0
         ..
555714    0
555715    0
555716    0
555717    0
555718    0
Name: is_fraud, Length: 555719, dtype: int64

In [20]:
#Feature Scaling – Standardization (To standardize Salary)
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
X= sc_x.fit_transform(X)
print(X)

[[-1.73204769 -0.31725171 -0.11966343 ...  0.5065263  -0.11878896
  -0.89397942]
 [-1.73204146 -0.31627306  1.23165562 ...  0.5065263  -0.11878896
  -0.89397942]
 [-1.73203522 -0.31625383  1.33101731 ...  0.5065263  -0.11878896
  -0.89397942]
 ...
 [ 1.73203522 -0.31441123  0.75968757 ...  1.6231831   1.49626514
   1.70110652]
 [ 1.73204146 -0.31899779 -1.3318761  ...  1.6231831   1.49626514
   1.70110652]
 [ 1.73204769 -0.31581678 -1.08347186 ...  1.6231831   1.49626514
   1.70110652]]


In [21]:
X

array([[-1.73204769, -0.31725171, -0.11966343, ...,  0.5065263 ,
        -0.11878896, -0.89397942],
       [-1.73204146, -0.31627306,  1.23165562, ...,  0.5065263 ,
        -0.11878896, -0.89397942],
       [-1.73203522, -0.31625383,  1.33101731, ...,  0.5065263 ,
        -0.11878896, -0.89397942],
       ...,
       [ 1.73203522, -0.31441123,  0.75968757, ...,  1.6231831 ,
         1.49626514,  1.70110652],
       [ 1.73204146, -0.31899779, -1.3318761 , ...,  1.6231831 ,
         1.49626514,  1.70110652],
       [ 1.73204769, -0.31581678, -1.08347186, ...,  1.6231831 ,
         1.49626514,  1.70110652]])

In [22]:
#Train Test Split Data 

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2)
print (X.shape)
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(555719, 26)
(444575, 26)
(111144, 26)
(444575,)
(111144,)


In [23]:
#Create Model 

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
print (lr)

LogisticRegression(max_iter=1000)


In [24]:
#Predict the Result (Test Data Set) 
y_pred= lr.predict(X_test)
print (y_pred)

[0 0 0 ... 0 0 0]


In [25]:
#Display y_test 
print (y_test)

494624    0
360122    0
488781    0
348697    0
415569    0
         ..
157727    0
547586    0
108956    0
272276    0
343323    0
Name: is_fraud, Length: 111144, dtype: int64


In [26]:
#Display Test and Prediction 
# Reset the indices of y_test and y_pred
y_test = y_test.reset_index(drop=True)
y_pred = pd.Series(y_pred)

# Create the DataFrame for display
df_result = pd.DataFrame({'Y_Test': y_test, 'Prediction': y_pred})
print(df_result.head(50))


    Y_Test  Prediction
0        0           0
1        0           0
2        0           0
3        0           0
4        0           0
5        0           0
6        0           0
7        0           0
8        0           0
9        0           0
10       0           0
11       0           0
12       0           0
13       0           0
14       0           0
15       0           0
16       0           0
17       0           0
18       0           0
19       0           0
20       0           0
21       0           0
22       0           0
23       0           0
24       0           0
25       0           0
26       0           0
27       0           0
28       0           0
29       0           0
30       0           0
31       0           0
32       0           0
33       0           0
34       0           0
35       0           0
36       0           0
37       0           0
38       0           0
39       0           0
40       0           0
41       0           0
42       0 

In [27]:
#Display Accuracy 
from sklearn.metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.9960771611602965


In [28]:
#Display Confusion Matrix 

from sklearn.metrics import confusion_matrix 
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[110708     24]
 [   412      0]]


In [29]:
#Display Classification Report 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred,zero_division=0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    110732
           1       0.00      0.00      0.00       412

    accuracy                           1.00    111144
   macro avg       0.50      0.50      0.50    111144
weighted avg       0.99      1.00      0.99    111144



In [30]:
#Prediction for Complete Data set  
y_pred= lr.predict(X)
print (y_pred)

[0 0 0 ... 0 0 0]


In [31]:
#Display Accuracy 
from sklearn.metrics import accuracy_score
print (accuracy_score (y,y_pred))

0.9958738139239436


In [32]:
#Display Confusion Matrix 

from sklearn.metrics import confusion_matrix 
cm = confusion_matrix (y,y_pred)
print (cm)

[[553426    148]
 [  2145      0]]


In [33]:
#Display Classification Report 
from sklearn.metrics import classification_report
print(classification_report (y,y_pred,zero_division = 0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.00      0.00      0.00      2145

    accuracy                           1.00    555719
   macro avg       0.50      0.50      0.50    555719
weighted avg       0.99      1.00      0.99    555719



In [34]:
df

Unnamed: 0            cc_num  merchant  category     amt  first  last  \
0                0  2291163933867244       319        10    2.86    151   115   
1                1  3573030041201292       591        10   29.84    163   457   
2                2  3598215285024754       611         5   41.28     24   249   
3                3  3591919803438423       222         9   60.05     42   457   
4                4  3526826139003047       292        13    3.19    247   261   
...            ...               ...       ...       ...     ...    ...   ...   
555714      555714    30560609640617       507         5   43.77    235   315   
555715      555715  3556613125071656       264         7  111.84    171   424   
555716      555716  6011724471098086       496         7   86.88     18   239   
555717      555717     4079773899158        75        13    7.99    111   342   
555718      555718  4170689372027579       125         0   38.13    280   145   

        gender  street  city  ...  trans_num   unix_time  merch_lat  \
0            1     341   157  ...      98699  1371816865  33.986391   
1            0     354    16  ...     108785  1371816873  39.450498   
2            0     865    61  ...     433979  1371816893  40.495810   
3            1     320   764  ...      71993  1371816915  28.812398   
4            1     548   247  ...     190585  1371816917  44.959148   
...        ...     ...   ...  ...        ...         ...        ...   
555714       1     531   443  ...     336391  1388534347  39.946837   
555715       1     540   401  ...      70372  1388534349  29.661049   
555716       0     126   104  ...     235088  1388534355  46.658340   
555717       1     663   476  ...      43546  1388534364  44.470525   
555718       1     778   224  ...      50595  1388534374  36.210097   

        merch_long  is_fraud  year  month  day  hour  minute  
0       -81.200714         0  2020      6   21    12      14  
1      -109.960431         0  2020      6   21    12      14  
2       -74.196111         0  2020      6   21    12      14  
3       -80.883061         0  2020      6   21    12      15  
4       -85.884734         0  2020      6   21    12      15  
...            ...       ...   ...    ...  ...   ...     ...  
555714  -91.333331         0  2020     12   31    23      59  
555715  -96.186633         0  2020     12   31    23      59  
555716 -119.715054         0  2020     12   31    23      59  
555717 -117.080888         0  2020     12   31    23      59  
555718  -97.036372         0  2020     12   31    23      59  

[555719 rows x 27 columns]